language: generic
sudo: required
services:
  - docker

  before_install:
  - docker build -t wer4arthou/docker-react -f Dockerfile.dev .


  script:
    - docker run -e CI=true wer4arthou/docker-react npm run test
    
